### ISSUE TITLE
DLL_NAME Error

### ISSUE THREAD

**Issue by shengruqing** [netpyoung/SqlCipher4Unity3D#19]
Assets\SqlCipher4Unity3D\Sqlite3.cs(125,20): error CS0103: The name 'DLL_NAME' does not exist in the current context

**Comment by shengruqing** [comment]
Windows has problems, android has no problems

**Comment by netpyoung** [comment]
Thank you for reporting.
I didn't build windows version. So that is what I missed. I will fix that code.

That caused by missing #if preprocessor directive.
https://github.com/netpyoung/SqlCipher4Unity3D/blob/c055fb352fcb629a2569d0d32808228bac023b53/SqlCipher4Unity3D/Assets/SqlCipher4Unity3D/Sqlite3.cs#L113

That line only handle UNITY_EDITOR, UNITY_ANDROID, UNITY_IOS.

**Comment by shengruqing** [comment]
thanks~
