### ISSUE TITLE
Can't Open DB file with DB Browser for SQLite

### ISSUE THREAD

**Issue by DanielTizon** [netpyoung/SqlCipher4Unity3D#37]
Hi,

And first of all, thanks for create this useful package for Unity, I have been able to start using it in just 5 min and everything is working flawless. From Unity, DB file is being used without problems, but when I try open this file with DB Browser for SQLite, it asks me for password and for "Encryption Settings". I have downloaded v1.1.1.unitypackage (for sqlcipher 4.x.x), so I select "SQLCipher 4 defaults", and I use my password, but I am not able to connect:

![image](https://user-images.githubusercontent.com/939005/111852631-fdc91900-8917-11eb-9db3-65692339272f.png)

Should I change any of the encryption settings or to do something else to do it works?

I'm using Ubuntu 20.04 LTS, but I don't know if it could be a problem,

Thanks!

**Comment by netpyoung** [comment]
your setting for sqlcipher option is looks correct. 
and I tested my https://github.com/netpyoung/SqlCipher4Unity3D/blob/f9819ce1128f1e930a78c98c8b82e8bd981fd05e/SqlCipher4Unity3D/Assets/StreamingAssets/existing.db . It can be opened.

Could you share your testable file?

**Comment by DanielTizon** [comment]
Yep, I'll send you it by email,

Thanks!

**Comment by netpyoung** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/issues/2162#issuecomment-622611160

I tested 2 versions(stable, nightly) and reproduce same bug.
- https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser
- https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing

the problem is both browser using sqlcipher 3.x version. so To upgrade latest version of sqlcipher4 you need to install nightly version of sqlcipher.

- https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlcipher-nightly

``` zsh
sudo add-apt-repository ppa:linuxgndu/sqlcipher-nightly
sudo apt-get update
```

then finally that file can be opened.

**Comment by DanielTizon** [comment]
It is working now :+1: 

Thanks!
